192.168.43.20919:04:26File Connect_Checker.py [INFO] NO REBOOT: credenciales correctas
